server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://postgres-siio.railway.internal:5432/railway
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://postgres-siio.railway.internal:5432/railway
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 60000
      ssl:
        enabled: true

services:
  config:
    url: ${SERVICE_CONFIG_URL}
