spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  r2dbc:
    url: ${R2_DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    url: ${DATABASE_URL}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude:
      - "org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration"
      - "org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration"
      - "org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration"

logging:
  level:
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    com.zaxxer.hikari: INFO

server:
  port: 9000

services:
  auth:
    url: https://auth-service-des.up.railway.app

app:
  jwt:
    secret: dev-secret-key-change-me-in-production-must-be-256-bits-long
    expiration-ms: 86400000
    issuer: mic-iamservice
