server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:${PGHOST:postgres-siio.railway.internal}}:${DB_PORT:${PGPORT:5432}}/${DB_NAME:${PGDATABASE:railway}}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USERNAME:${PGUSER:postgres}}
    password: ${DB_PASSWORD:${PGPASSWORD:}}
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:${PGHOST:postgres-siio.railway.internal}}:${DB_PORT:${PGPORT:5432}}/${DB_NAME:${PGDATABASE:railway}}?schema=${DB_SCHEMA:public}
    username: ${DB_USERNAME:${PGUSER:postgres}}
    password: ${DB_PASSWORD:${PGPASSWORD:}}
  data:
    redis:
      host: ${REDIS_HOST:redis.railway.internal}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 60000
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
  liquibase:
    enabled: true
    default-schema: ${DB_SCHEMA:public}

services:
  config:
    url: ${SERVICE_CONFIG_URL}
