package com.backandwhite.api.dto;

import java.time.ZonedDateTime;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.With;

/**
 * Standard error response DTO for the API Gateway.
 *
 * <p>
 * Provides a uniform structure for all errors generated by the gateway, both at
 * the controller and routing levels.
 *
 * @author NX036-ALFA
 */
@Data
@With
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GatewayErrorResponseDto {

    private String code;
    private String message;
    private List<String> details;
    private ZonedDateTime dateTime;
}
